# Generated by Django 5.0.7 on 2024-07-31 17:05

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('url', models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('published_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('edit_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('admin_solve_text', models.TextField(blank=True, null=True)),
                ('grade', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('dislike_num', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCommentNegativePointsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCommentPositivePointsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField(verbose_name='مقدار')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/product_images', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('url', models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='product/product_images', verbose_name='تصویر')),
                ('published_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('price_after_off', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت بعد از تخفیف')),
                ('view_num', models.PositiveIntegerField(verbose_name='تعداد بازدید')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('sell', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='product/product_videos', verbose_name='ویدیو')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ای پی')),
                ('date_view', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('url', models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='product.childcategorymodel', verbose_name='دسته بندی پدر')),
                ('base_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_category_child', to='product.maincategorymodel', verbose_name='دسته بندی اصلی')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategoryImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/category', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('child_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_category_image', to='product.childcategorymodel', verbose_name='دسته بندی فرزند')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFiledModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('category', models.ManyToManyField(related_name='child_category_field', to='product.childcategorymodel', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='product/brands_image', verbose_name='تصویر')),
                ('url', models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ManyToManyField(related_name='category_brands', to='product.childcategorymodel', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategoryImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/category', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('main_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_category_image', to='product.maincategorymodel', verbose_name='دسته بندی اصلی')),
            ],
        ),
    ]
