# Generated by Django 5.0.7 on 2024-07-31 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='admin_seen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_seen_product_comments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی ادمین'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='admin_solve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_solve_product_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='productcommentnegativepointsview',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_negative_points', to='product.productcommentmodel'),
        ),
        migrations.AddField(
            model_name='productcommentpositivepointsview',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_positive_points', to='product.productcommentmodel'),
        ),
        migrations.AddField(
            model_name='productfieldmodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='product.categoryfiledmodel', verbose_name='فیلد'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands_products', to='product.brandmodel', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='child_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_category_products', to='product.childcategorymodel', verbose_name='دسته بندی فرزند'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_category_products', to='product.maincategorymodel', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productfieldmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fields', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productpricechartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_chart', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productvideomodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_video', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_view', to='product.productmodel', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_view', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='userfavoriteproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='userfavoriteproductmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_product', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
