# Generated by Django 5.0.7 on 2024-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategoryimagemodel',
            name='main_category',
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='product/category', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='maincategorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='product/category', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChildCategoryImageModel',
        ),
        migrations.DeleteModel(
            name='MainCategoryImageModel',
        ),
    ]
