# Generated by Django 5.0.7 on 2024-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='panel/banners')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('logo', models.ImageField(upload_to='site_detail/image')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('empty_cart_image', models.ImageField(upload_to='site_detail/image')),
                ('footer_title', models.CharField(max_length=1000)),
                ('footer_text', models.TextField()),
                ('copy_right', models.TextField()),
                ('enamad_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('enamad_url', models.URLField(blank=True, null=True)),
                ('kasbokar_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('kasbokar_url', models.URLField(blank=True, null=True)),
                ('samandehi_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('samandehi_url', models.URLField(blank=True, null=True)),
                ('limit_of_address_can_add', models.IntegerField()),
                ('suggested_products_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('amazing_products_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
