# Generated by Django 5.0.7 on 2024-07-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetailmodel',
            old_name='footer_text',
            new_name='work_time',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='footer_title',
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='fax',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
