# Generated by Django 5.0.7 on 2024-07-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='position_y',
        ),
    ]
